spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.68.51.99:3300/exposure
    username: root
    password: 123456
  redis:
    host: 10.22.59.82
    port: 6379
    password: HuaWei!@#123

server:
   port: 5552
spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

security:
  sessions: NEVER
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.68.51.99:8764/eureka/